### ISSUE TITLE
Aerospike Timeout issue

### ISSUE THREAD

**Issue by vivek9716** [aerospike/aerospike-session-store-expressjs#11]
Why I am getting these error not found any solution for this :

ERROR(1696) [command.cc:84] [ErrorCallback] - Client error in Put command: Socket read failed: -4095 [-6]
0| 2018-08-16 15:13 +05:30: AerospikeError: Socket read failed: -4095

WARN (3103) [as_cluster.c:564] [as_cluster_tend] - Node BB90C5988565000 peers refresh failed: AEROSPIKE_ERR_TIMEOUT

Please revert as soon as possible.

**Comment by vivek9716** [comment]
Please tell me why I am getting this error and what is the solution :
AerospikeError: Client timeout: iterations=1 lastNode=XXX.XX.XX.XX:3000
    at Function.fromASError (/node_modules/aerospike/lib/error.js:113:19)
    at GetCommand.convertError (node_modules/aerospike/lib/commands/command.js:89:27)
    at GetCommand.convertResponse (node_modules/aerospike/lib/commands/command.js:99:22)
    at asCallback (/node_modules/aerospike/lib/commands/command.js:161:22)

**Comment by jhecking** [comment]
Sounds like you are having network issues which is causing timeouts. Try increasing the client timeouts (connection timeouts as well as session read/write timeouts):

```javascript
const session = require('express-session')
const AerospikeStore = require('aerospike-session-store')(session)

const defaultPolicy = {
  totalTimeout: 2000, // in ms, default is 1000 ms
  socketTimeout: 1000, // in ms, default is zero
  maxRetries: 2
}

const config = {
  namespace: 'express',
  set: 'session',
  ttl: 86400, // 1 day
  hosts: '10.0.0.1:3000,10.0.0.2:3000',
  connTimeoutMs: 2000, // in ms, default is 1000 ms
  policies: {
    read: defaultPolicy,
    write: defaultPolicy
  }
}

const app = express()
app.use(session({
  secret: '123456789QWERTY',
  store: new AerospikeStore(config)
}))
```

Please refer to the [Aerospike client docs](https://www.aerospike.com/apidocs/nodejs/BasePolicy.html) for details about configuring the read/write policies.

**Comment by jhecking** [comment]
@vivek9716, have you been able to resolve this issue?

**Comment by vivek9716** [comment]
Yes, it is now working on production but on my local it sometimes timeout.
