### ISSUE TITLE
Is package on npm?

### ISSUE THREAD

**Issue by apsavin** [aerospike/aerospike-session-store-expressjs#2]
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/aerospike-session-store
npm ERR! 404 
npm ERR! 404 'aerospike-session-store' is not in the npm registry.

**Comment by jhecking** [comment]
Hi @apsavin,

This package is now available from [npmjs.org](https://www.npmjs.com/package/aerospike-session-store).
